defmodule SlipdockWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :slipdock

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_slipdock_key",
    signing_salt: "wli8+OGq",
    same_site: "Lax",
    max_age: 60 * 60 * 24 * 30
  ]

  # The peer and the X- headers are for `SlipdockWeb.ClientIP`: the sign-in
  # page rate-limits by the visitor's address, which a connected LiveView
  # otherwise cannot see.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [:peer_data, :x_headers, session: @session_options]],
    longpoll: [connect_info: [:peer_data, :x_headers, session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  # The session cookie is `Secure` whenever this server says its address is
  # https, so a browser never sends it over plain http — where anybody on the
  # path could lift it and be signed in. Read per request rather than fixed at
  # compile time because the scheme is runtime configuration
  # (`SLIPDOCK_URL_SCHEME`); both forms are built once, here.
  @plain_session Plug.Session.init(@session_options)
  @secure_session Plug.Session.init(Keyword.put(@session_options, :secure, true))

  defp session(conn, _opts) do
    opts = if config(:url)[:scheme] == "https", do: @secure_session, else: @plain_session
    Plug.Session.call(conn, opts)
  end

  plug Plug.Static,
    at: "/",
    from: :slipdock,
    gzip: not code_reloading?,
    only: SlipdockWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :slipdock
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug :parse_body

  @parsers Plug.Parsers.init(
             # Multipart bodies stream to temporary files, so a meeting's
             # recording (see `Slipdock.Meetings.Limits`) can be this large
             # without being held in memory; the 8 MB default refused it.
             parsers: [:urlencoded, {:multipart, length: 520_000_000}, :json],
             pass: ["*/*"],
             json_decoder: Phoenix.json_library()
           )

  # `/mcp` reads its own body. JSON-RPC has its own answer to a body that is
  # not JSON (`-32700`), and `Plug.Parsers` would raise a 400 HTML page first.
  defp parse_body(%Plug.Conn{path_info: ["mcp"]} = conn, _opts), do: conn
  # Runners send their logs as plain text from `curl`, whose default content
  # type would otherwise have the form parser eat them.
  defp parse_body(%Plug.Conn{path_info: ["api", "runner" | _]} = conn, _opts),
    do: Plug.Conn.fetch_query_params(conn)

  defp parse_body(conn, _opts), do: Plug.Parsers.call(conn, @parsers)

  plug Plug.MethodOverride
  plug Plug.Head
  plug :session
  plug SlipdockWeb.Router
end
