import Config

# Configure your database. A Postgres on localhost:5434 is what
# `docker compose -f compose.dev.yaml up -d` gives you; DATABASE_URL points
# this somewhere else — handy for a throwaway copy (the demo workspace behind
# the README screenshots, say) without disturbing the one you work in.
config :slipdock, Slipdock.Repo,
  url:
    System.get_env("DATABASE_URL") || "postgres://postgres:postgres@localhost:5434/slipdock_dev",
  pool_size: 10,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# Pick the address the dev server listens on: SLIPDOCK_BIND_IP if set,
# otherwise this machine's Tailscale IPv4, otherwise loopback. Preferring
# Tailscale is a convenience, not a requirement — it means a machine on a
# tailnet is reachable from your other devices and from nowhere else, and a
# machine without Tailscale quietly gets 127.0.0.1. Set SLIPDOCK_BIND_IP to
# 0.0.0.0 for every interface, or to 127.0.0.1 to be sure of loopback.
tailscale_ip =
  with exe when is_binary(exe) <- System.find_executable("tailscale"),
       {out, 0} <- System.cmd(exe, ["ip", "-4"], stderr_to_stdout: true),
       [ip | _] <- String.split(out, "\n", trim: true) do
    ip
  else
    _ -> nil
  end

{:ok, bind_ip} =
  (System.get_env("SLIPDOCK_BIND_IP") || tailscale_ip || "127.0.0.1")
  |> String.trim()
  |> String.to_charlist()
  |> :inet.parse_address()

# The mailbox at /dev/mailbox and Phoenix's debug error pages are for a
# developer's own machine: the mailbox shows anyone who can reach it every
# sign-in link this server has "sent". SLIPDOCK_DEV_TOOLS=false turns both off
# for a dev-mode server other people can reach — though such a server should
# be running the release instead (deploy/slipdock.service).
dev_tools = System.get_env("SLIPDOCK_DEV_TOOLS") not in ["0", "false"]

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :slipdock, SlipdockWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # Bind to the Tailscale interface only (this machine also has a public
  # address and no firewall). Override with SLIPDOCK_BIND_IP=0.0.0.0 to listen
  # everywhere, or SLIPDOCK_BIND_IP=127.0.0.1 for loopback only.
  http: [ip: bind_ip, port: String.to_integer(System.get_env("PORT") || "4000")],
  # Links in emails (magic sign-in) must point at the address people use.
  url: [
    host: System.get_env("SLIPDOCK_URL_HOST") || tailscale_ip || "localhost",
    port: String.to_integer(System.get_env("PORT") || "4000")
  ],
  check_origin: false,
  code_reloader: true,
  debug_errors: dev_tools,
  secret_key_base: "9dTyyUQKRD2HAVJoLDGYzmBm4/CZm9sOhpmQVEYWIDmSiczWvLRoxvxOZ4ow6I3Q",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:slipdock, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:slipdock, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :slipdock, dev_routes: dev_tools

# "Agentic Login" on the sign-in page: writes a one-time sign-in link to a
# file under this directory instead of emailing it, so an automated agent
# with shell access can read the file and follow the link. The file is mode
# 0600, in a private directory under the system temp dir unless
# SLIPDOCK_AGENTIC_LOGIN_DIR says otherwise (see `Accounts.agentic_login_dir/0`).
config :slipdock, agentic_login: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
