import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :slipdock, SlipdockWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
#
# `:force_ssl` is read at compile time, so this is settled when the release is
# built, not when it runs: SLIPDOCK_FORCE_SSL=false at *build* time leaves it off.
# The Docker image does exactly that, because a container is normally reached
# through somebody else's proxy and an unconditional redirect to https inside it
# is how you get a redirect loop. If you terminate TLS at the app itself, build
# with it on (the default) and make sure your proxy sets x-forwarded-proto.
if System.get_env("SLIPDOCK_FORCE_SSL") != "false" do
  config :slipdock, SlipdockWeb.Endpoint,
    force_ssl: [
      rewrite_on: [:x_forwarded_proto],
      exclude: [
        # paths: ["/health"],
        hosts: ["localhost", "127.0.0.1"]
      ]
    ]
end

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
